"""add_protocol_decisions_table

Revision ID: 8cd806dc7e3d
Revises: 56159e4d40d2
Create Date: 2026-09-11 02:32:10.787612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd806dc7e3d'
down_revision: Union[str, None] = '56159e4d40d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('observed_action', sa.String(length=64), nullable=False),
    sa.Column('expected_actions', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=False),
    sa.Column('debounce_count', sa.Integer(), nullable=False),
    sa.Column('debounce_threshold', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('retroactive_skips', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_decisions_decision_id'), 'protocol_decisions', ['decision_id'], unique=True)
    op.create_index(op.f('ix_protocol_decisions_experiment_id'), 'protocol_decisions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_protocol_decisions_run_id'), 'protocol_decisions', ['run_id'], unique=False)
    op.create_index(op.f('ix_protocol_decisions_status'), 'protocol_decisions', ['status'], unique=False)
    op.create_index(op.f('ix_protocol_decisions_step_id'), 'protocol_decisions', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protocol_decisions_step_id'), table_name='protocol_decisions')
    op.drop_index(op.f('ix_protocol_decisions_status'), table_name='protocol_decisions')
    op.drop_index(op.f('ix_protocol_decisions_run_id'), table_name='protocol_decisions')
    op.drop_index(op.f('ix_protocol_decisions_experiment_id'), table_name='protocol_decisions')
    op.drop_index(op.f('ix_protocol_decisions_decision_id'), table_name='protocol_decisions')
    op.drop_table('protocol_decisions')
    # ### end Alembic commands ###
